### ISSUE TITLE
music-client启动错误

### ISSUE THREAD

**Issue by Mefa3** [Yin-Hongwei/music-website#309]
npm run serve 后就这样了
![image](https://github.com/user-attachments/assets/d2a5ff3a-d529-4e9e-82fe-959f2dfa6760)

**Comment by KissMyLady** [comment]
# 👏👏解决方法: 重新安装vue-router

重新安装
```sh
npm install vue-router@4.0.3
```

启动成功
```js
 DONE  Compiled successfully in 27444ms                             
                                                                    
                                                                    
  App running at:                                                   
  - Local:   http://localhost:8080/                                 
  - Network: http://192.168.1.108:8080/                             
                                                                    
  Note that the development build is not optimized.                 
  To create a production build, run npm run build.                  
                                                                    
No issues found.                                                    
```

**Comment by KissMyLady** [comment]
# 🐛🐛编译bug: 启动成功后, 编译失败

<br/>

环境
```js
os: centos8.5
node: v14.21.3
npm: 6.14.18
```

<br/>

编译返回
```js
root@centos8:music-client # npm run build

> music-client@3.0.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠼  Building for production...[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead of ::v-deep <inner-selector>.

⠧  Building for production...[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead of ::v-deep <inner-selector>.

⠼  Building for production...


 ERROR  Failed to compile with 4 errors                                                                                            17:35:08

 error  in node_modules/@types/lodash/common/common.d.ts:266:65

TS1005: '?' expected.
    264 |         [P in keyof T]?: T[P] extends object ? object : T[P]
    265 |     };
  > 266 |     type StringToNumber<T> = T extends `${infer N extends number}` ? N : never;
        |                                                                 ^
    267 |     // For backwards compatibility
    268 |     type LoDashImplicitArrayWrapper<T> = LoDashImplicitWrapper<T[]>;
    269 |     type LoDashImplicitNillableArrayWrapper<T> = LoDashImplicitWrapper<T[] | null | undefined>;

 error  in node_modules/@types/lodash/common/object.d.ts:1026:46

TS1005: '?' expected.
    1024 |     type GetFieldTypeOfArrayLikeByKey<T extends unknown[], K> =
    1025 |         K extends number ? T[K]
  > 1026 |         : K extends `${infer N extends number}` ? T[N]
         |                                              ^
    1027 |         : K extends keyof T ? T[K] : undefined;
    1028 |
    1029 |     type GetFieldTypeOfStringByKey<T extends string, K> =

 error  in node_modules/@types/lodash/common/object.d.ts:1031:46

TS1005: '?' expected.
    1029 |     type GetFieldTypeOfStringByKey<T extends string, K> =
    1030 |         K extends number ? T[K]
  > 1031 |         : K extends `${infer N extends number}` ? T[N]
         |                                              ^
    1032 |         : K extends keyof T ? T[K]
    1033 |         : undefined;
    1034 |

 error  in node_modules/@types/lodash/common/object.d.ts:1041:46

TS1005: '?' expected.
    1039 |         : K extends number
    1040 |             ? `${K}` extends keyof T ? T[`${K}`] : undefined
  > 1041 |         : K extends `${infer N extends number}`
         |                                              ^
    1042 |             ? N extends keyof T ? T[N] : undefined
    1043 |         : undefined;
    1044 |

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /root/code/music-website/music-client/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /root/code/music-website/music-client/node_modules/webpack/lib/webpack.js:167:8
    at /root/code/music-website/music-client/node_modules/webpack/lib/HookWebpackError.js:68:2
    at Hook.eval [as callAsync] (eval at create (/root/code/music-website/music-client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/root/code/music-website/music-client/node_modules/tapable/lib/Hook.js:20:14)
    at Cache.shutdown (/root/code/music-website/music-client/node_modules/webpack/lib/Cache.js:156:23)
    at /root/code/music-website/music-client/node_modules/webpack/lib/Compiler.js:1406:15
    at Hook.eval [as callAsync] (eval at create (/root/code/music-website/music-client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/root/code/music-website/music-client/node_modules/tapable/lib/Hook.js:20:14)
    at Compiler.close (/root/code/music-website/music-client/node_modules/webpack/lib/Compiler.js:1399:23)
    at /root/code/music-website/music-client/node_modules/webpack/lib/webpack.js:166:16
    at finalCallback (/root/code/music-website/music-client/node_modules/webpack/lib/Compiler.js:521:32)
    at /root/code/music-website/music-client/node_modules/webpack/lib/Compiler.js:545:13
    at Hook.eval [as callAsync] (eval at create (/root/code/music-website/music-client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/root/code/music-website/music-client/node_modules/tapable/lib/Hook.js:20:14)
    at onCompiled (/root/code/music-website/music-client/node_modules/webpack/lib/Compiler.js:543:21)
    at /root/code/music-website/music-client/node_modules/webpack/lib/Compiler.js:1377:17
    at eval (eval at create (/root/code/music-website/music-client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
