### ISSUE TITLE
启动客户端问题

### ISSUE THREAD

**Issue by fanruohongclub** [Yin-Hongwei/music-website#32]
1.运行完npm install，再运行npm run dev时候报错了。
内容如下：
 ERROR  Failed to compile with 29 errors                                                                        10:31:36
 error  in ./src/assets/css/index.scss

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:872:3)
    at Object.getInstalledBinaries (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\extensions.js:133:13)
    at foundBinariesList (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\binding.js:15:30)    at Object.<anonymous> (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at getDefaultSassImpl (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\sass-loader\dist\index.js:198:10)
    at Object.loader (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\sass-loader\dist\index.js:80:29)
 @ ./src/assets/css/index.scss 4:14-207 13:3-17:5 14:22-215
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./src/pages/404.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:872:3)
    at Object.getInstalledBinaries (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\extensions.js:133:13)
    at foundBinariesList (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\binding.js:15:30)    at Object.<anonymous> (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at getDefaultSassImpl (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\sass-loader\dist\index.js:198:10)
    at Object.loader (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\sass-loader\dist\index.js:80:29)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-d989eb38","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/404.vue 4:14-368 13:3-17:5 14:22-376
 @ ./src/pages/404.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./src/App.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:872:3)
    at Object.getInstalledBinaries (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\extensions.js:133:13)
    at foundBinariesList (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\binding.js:15:30)    at Object.<anonymous> (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at getDefaultSassImpl (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\sass-loader\dist\index.js:198:10)
    at Object.loader (E:\写程序软件\node.js\node\node_modules\music-client\node_modules\sass-loader\dist\index.js:80:29)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-356 13:3-17:5 14:22-364
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

。。。。。。。。。。。。。。。。。。。。。。。。。内容还好多。。。。。。。。。。。。。。。。。。。。。。。。。。
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

2.启动之后，进入首页的地址是多少？

**Comment by Yin-Hongwei** [comment]
1、问题1是 node-sass 这个包没有下下来，你把node_modules删了，执行一下下面这个命令
npm config set sass_binary_site=https://npm.taobao.org/mirrors/node-sass，然后再执行 npm i。再运行npm run dev 启动一下。
2、问题2的话你启动起来终端会给你一个访问地址的，你点那个就行了

**Comment by fanruohongclub** [comment]
ok了
